name: Checks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  checks:

    name: Periodic Checks
    runs-on: ubuntu-22.04

    steps:

      - name: Check Broken Links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://tinylog.org/
          cmd_params: "--max-connections-per-host=1 --rate-limit=1 --buffer-size=8192 --header=User-Agent:Wget --color=always"
