name: Checks

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  checks:

    name: Periodic Checks
    runs-on: ubuntu-22.04

    steps:

      - name: Check Broken Links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://tinylog.org/
          cmd_params: "--exclude=(baeldung.com|mkyong.com|gmarket.com) --max-connections-per-host=1 --rate-limit=1 --header=User-Agent:Mozilla/5.0 --color=always"
